### ISSUE TITLE
Respect `event.preventDefault()` for pointer events

### ISSUE THREAD

**Issue by kripod** [stevejay/react-roving-tabindex#33]
When `event.preventDefault()` is called in a button’s `onMouseDown(event)` callback, then the given button should not receive focus. This is desired in text editing scenarios where the toolbar should only be focused on direct keyboard interactions with it, e.g. [within Slate](https://www.slatejs.org/examples/richtext) _(see the [source](https://github.com/ianstormtaylor/slate/blob/2bba0e68c6df79dd5657011c11a37bf49be73fea/site/examples/richtext.tsx#L169) for implementation details)._

The value of `focused` returned by `useRovingTabIndex` should be set to null when a click isn’t keyboard-initiated (not handled by `handleKeyDown`, but **only** through `handleClick`). By applying that behavior, `useFocusEffect` will not (re)focus a button unnecessarily, especially when `onClick` is invoked by a pointing device.

**Comment by stevejay** [comment]
Fixed in #38
