### ISSUE TITLE
Vertical navigation

### ISSUE THREAD

**Issue by steida** [stevejay/react-roving-tabindex#4]
I was using "out of React" roving-tabindex implementation until I realized that it's very brittle because the focused component can be removed and then is no tab indexable component anymore.

If I will find spare time, I will send PR with logic for vertical navigation based on size and position as can be seen here: https://github.com/este/este/blob/master/packages/components/KeyboardNavigableView.tsx

**Comment by stevejay** [comment]
I suspect this library isn't going to be the best fit for your needs. It looks like you need horizontal and vertical movement of the focussed input, but this library is about a single dimension of movement so its use of the compareDocumentPosition browser API works fine for establishing correct tab order at all times. This wouldn't be the case with a 2D movement scenario.

**Comment by steida** [comment]
Just for fun, I reimplemented it https://gist.github.com/steida/6131d5ee0d150516923932b05a579255
