### ISSUE TITLE
loopAround doesn't loop if first/last tabStop is disabled

### ISSUE THREAD

**Issue by bfeigin** [stevejay/react-roving-tabindex#43]
## Detailed Description
When the `loopAround` option is set to `true` I'd expect the selection to loop regardless of the leading / trailing tabStops being enabled or not. 

For example: 

**Given**: 
- The last "enabled" tabStop in the list is selected
- The last tabStop in the list is disabled
- The ArrowRight key (assuming horizontal direction) is pressed

**Then:** 
- I would expect the selection to "loopAround" to the first "enabled" tabStop.

**However currently:** 
- The selection is not changed.

This appears to break the loopAround expected behavior.

## Possible Implementation
If this is deemed a valid issue I'm happy to open a PR this patch https://github.com/bfeigin/react-roving-tabindex/commit/7f38d030ea74508c5c3e678fa11c07f8ba7f5222
Currently I have the tests building from a parameterized function. I'd be happy to explicitly spread the examples out over each state case if that's desired and idiomatic for the repo, but wanted to validate the approach and functionality first.

Cheers!

**Comment by stevejay** [comment]
Thanks for the detailed bug report and PR! I've created a [new PR containing your fix](https://github.com/stevejay/react-roving-tabindex/pull/44) - I refactored the code a bit and the tests I added are consistent with the existing testing style. It would be great if you could please review it.

**Comment by stevejay** [comment]
@bfeigin Bugfix released as version 3.1.1
